CREATE TABLE Cricket_info(id int,player_id int, player_name varchar(30),  Age INT,team varchar(50), matches_played int,
runs int, wickets int, batting_avg decimal(5,2), bowling_avg decimal(5,2), role varchar(50));
SELECT * FROM Cricket_info;
INSERT INTO Cricket_info values(1,1, 'Virat Kohli', 35, 'India', 250, 12000, 4, 57.3, 100.5, 'Batsman');
INSERT Into Cricket_info values(2, 2, 'Steve Smith', 34, 'Australia', 180, 9500, 2, 60.1, 90.4, 'Batsman');
INSERT INTO Cricket_info values(3,3, 'Jasprit Bumrah', 30, 'India', 120, 500, 250, 19.2, 24.3, 'Bowler');
INSERT INTO Cricket_info values(4,4, 'Joe Root', 33, 'England', 200, 10500, 30, 50.2, 45.7, 'Batsman');
INSERT INTO Cricket_info values(5,5, 'Ben Stokes', 32, 'England', 170, 5500, 170, 40.8, 32.5, 'All-rounder');
INSERT INTO Cricket_info values(6,6, 'Kane Williamson', 34, 'New Zealand', 150, 8000, 5, 53.9, 98.7, 'Batsman');
INSERT INTO Cricket_info values(7,7, 'David Warner', 37, 'Australia', 180, 8500, 3, 48.5, 101.2, 'Batsman');
INSERT INTO Cricket_info values(8,8, 'Marnus Labuschagne', 30, 'Australia', 100, 6000, 12, 52.8, 85.3, 'Batsman');
INSERT INTO Cricket_info values(9,9, 'Shakib Al Hasan', 38, 'Bangladesh', 220, 7000, 300, 38.6, 30.8, 'All-rounder');
INSERT INTO Cricket_info values( 10,10, 'Trent Boult', 35, 'New Zealand', 140, 200, 280, 15.3, 22.7, 'Bowler');
INSERT INTO Cricket_info values(11,11, 'Pat Cummins', 33, 'Australia', 130, 1200, 240, 25.6, 21.2, 'Bowler');
INSERT INTO Cricket_info values(12,12, 'Ravindra Jadeja', 34, 'India', 190, 4500, 230, 42.3, 26.4, 'All-rounder');
INSERT INTO Cricket_info values(13,13, 'Babar Azam', 30, 'Pakistan', 160, 7500, 0, 56.8, NULL, 'Batsman');
INSERT INTO Cricket_info values(15,15, 'Andre Russell', 36, 'West Indies', 140, 2500, 180, 29.3, 28.6, 'All-rounder');
ALTER TABLE Cricket_info ADD (Strike_Rate DECIMAL(5,2), Economy DECIMAL(5,2));
ALTER TABLE Cricket_info RENAME COLUMN Batting_Avg TO Bat_Avg;
ALTER TABLE Cricket_info RENAME COLUMN Bowling_Avg TO Bowl_Avg;
UPDATE Cricket_info SET Runs = 12500, Bat_Avg = 58.4 WHERE Player_Name = 'Virat Kohli' AND Team = 'India';
UPDATE Cricket_info SET Matches_Played = 185 WHERE Player_Name = 'Steve Smith' OR Team = 'Australia';
UPDATE Cricket_info SET Wickets = 260 WHERE Player_ID IN (3, 10, 11);
UPDATE Cricket_info SET Role = 'Captain' WHERE Player_Name NOT IN ('Babar Azam', 'Quinton de Kock');
DELETE FROM Cricket_info WHERE Player_ID = 15;
DELETE FROM Cricket_info WHERE Player_Name = 'David Warner';
DELETE FROM Cricket_info WHERE Team = 'Bangladesh';
SELECT * FROM Cricket_info WHERE Age > 30;
SELECT * FROM Cricket_info WHERE Age BETWEEN 30 AND 35;
SELECT * FROM Cricket_info WHERE Team IN ('India', 'Australia');
SELECT * FROM Cricket_info WHERE Team NOT IN ('Bangladesh', 'West Indies');
SELECT * FROM Cricket_info WHERE Player_Name LIKE 'V%';
SELECT * FROM Cricket_info WHERE Player_Name NOT LIKE 'S%';
CREATE TABLE Football_info (Player_ID INT PRIMARY KEY,Player_Name VARCHAR(50),Age INT,Team VARCHAR(50),Matches_Played INT,
Goals INT,Assists INT,Yellow_Cards INT,Red_Cards INT,Position VARCHAR(50));
INSERT INTO Football_info VALUES(1, 'Lionel Messi', 37, 'Argentina', 1000, 750, 300, 50, 2, 'Forward');
INSERT INTO Football_info VALUES(2, 'Cristiano Ronaldo', 39, 'Portugal', 1200, 820, 250, 55, 5, 'Forward');
INSERT INTO Football_info VALUES(4, 'Kylian Mbappe', 28, 'France', 500, 300, 150, 20, 1, 'Forward');
INSERT INTO Football_info VALUES(5, 'Kevin De Bruyne', 35, 'Belgium', 700, 150, 350, 30, 1, 'Midfielder');
INSERT INTO Football_info VALUES(6, 'Luka Modric', 38, 'Croatia', 850, 130, 280, 25, 0, 'Midfielder');
INSERT INTO Football_info VALUES(7, 'Virgil van Dijk', 34, 'Netherlands', 600, 50, 20, 10, 0, 'Defender');
INSERT INTO Football_info VALUES(8, 'Sergio Ramos', 39, 'Spain', 900, 80, 50, 60, 8, 'Defender');
INSERT INTO Football_info VALUES(9, 'Harry Kane', 32, 'England', 700, 400, 100, 15, 0, 'Forward');
INSERT INTO Football_info VALUES(10, 'Mohamed Salah', 33, 'Egypt', 680, 350, 120, 18, 1, 'Forward');
INSERT INTO Football_info VALUES(11, 'Robert Lewandowski', 37, 'Poland', 850, 600, 150, 20, 2, 'Forward');
INSERT INTO Football_info VALUES(12, 'Bruno Fernandes', 30, 'Portugal', 550, 180, 200, 25, 0, 'Midfielder');
INSERT INTO Football_info VALUES(13, 'Erling Haaland', 28, 'Norway', 300, 250, 50, 5, 0, 'Forward');
INSERT INTO Football_info VALUES(14, 'Jude Bellingham', 25, 'England', 200, 50, 80, 8, 0, 'Midfielder');
INSERT INTO Football_info VALUES(15, 'Alphonso Davies', 27, 'Canada', 400, 20, 100, 5, 0, 'Defender');
ALTER TABLE Football_info ADD (Pass_Accuracy DECIMAL(5,2), Tackles INT);
ALTER TABLE Football_info RENAME COLUMN Yellow_Cards TO Y_Cards;
ALTER TABLE Football_info RENAME COLUMN Red_Cards TO R_Cards;
UPDATE Football_info SET Goals = 830 WHERE Player_Name = 'Cristiano Ronaldo' AND Team = 'Portugal';
UPDATE Football_info SET Assists = 155 WHERE Player_ID IN (4, 12, 13);
UPDATE Football_info SET Position = 'Attacker' WHERE Team NOT IN ('Portugal', 'Brazil');
UPDATE Football_info SET Pass_Accuracy = 90.5 WHERE Player_Name LIKE 'Kevin%';
DELETE FROM Football_info WHERE Player_ID = 14;
DELETE FROM Football_info WHERE Player_Name = 'Virgil van Dijk';
DELETE FROM Football_info WHERE Team = 'Canada';
SELECT * FROM Football_info WHERE Age < 35;
SELECT * FROM Football_info WHERE Matches_Played BETWEEN 500 AND 1000;
SELECT * FROM Football_info WHERE Position IN ('Forward', 'Midfielder');
SELECT * FROM Football_info WHERE Position NOT IN ('Defender', 'Goalkeeper');
SELECT * FROM Football_info WHERE Player_Name LIKE '%o%';
SELECT * FROM Football_info WHERE Player_Name NOT LIKE '%e%';


